/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visor;

import Calculadora.Calc;
import Info.Mais;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author Caique
 */
public class tela extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        Abrir = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        Fonte = new javax.swing.JButton();
        Fonte1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar1.setFloatable(false);
        jToolBar1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(60, 61, 64));

        Abrir.setBackground(new java.awt.Color(45, 46, 46));
        Abrir.setForeground(new java.awt.Color(255, 255, 255));
        Abrir.setIcon(new javax.swing.ImageIcon("D:\\Projetos\\Java\\EditorTexto\\src\\main\\java\\Icones\\Abrir.png")); // NOI18N
        Abrir.setText("Abrir");
        Abrir.setFocusable(false);
        Abrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Abrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });

        Salvar.setBackground(new java.awt.Color(51, 53, 54));
        Salvar.setForeground(new java.awt.Color(255, 255, 255));
        Salvar.setIcon(new javax.swing.ImageIcon("D:\\Projetos\\Java\\EditorTexto\\src\\main\\java\\Icones\\salvar.png")); // NOI18N
        Salvar.setText("Salvar");
        Salvar.setFocusable(false);
        Salvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        Fonte.setBackground(new java.awt.Color(51, 53, 54));
        Fonte.setForeground(new java.awt.Color(255, 255, 255));
        Fonte.setIcon(new javax.swing.ImageIcon("D:\\Projetos\\Java\\EditorTexto\\src\\main\\java\\Icones\\Fonte.png")); // NOI18N
        Fonte.setText("Titulo");
        Fonte.setFocusable(false);
        Fonte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Fonte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Fonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FonteActionPerformed(evt);
            }
        });

        Fonte1.setBackground(new java.awt.Color(51, 53, 54));
        Fonte1.setForeground(new java.awt.Color(255, 255, 255));
        Fonte1.setIcon(new javax.swing.ImageIcon("D:\\Projetos\\Java\\EditorTexto\\src\\main\\java\\Icones\\Mais.png")); // NOI18N
        Fonte1.setText("Info");
        Fonte1.setFocusable(false);
        Fonte1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Fonte1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Fonte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fonte1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Abrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salvar)
                .addGap(18, 18, 18)
                .addComponent(Fonte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fonte1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Abrir)
                    .addComponent(Salvar)
                    .addComponent(Fonte)
                    .addComponent(Fonte1))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        Abrir.getAccessibleContext().setAccessibleDescription("");

        display.setContentType("text/html"); // NOI18N
        display.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        display.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        display.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                displayKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                displayKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                displayKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(display);
        display.getAccessibleContext().setAccessibleDescription("text/html");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        display.setContentType("text/html");
      /*  display.setText("<html><head><style type='text/css'>"
            + "body{white-space:nowrap;}"
            + "</style></head><body>");*/
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void FonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FonteActionPerformed
        // TODO add your handling code here:
        /* String TextoSelecionado = display.getSelectedText();
        TextoSelecionado = "<fonte>"+ TextoSelecionado +"";*/
        Font.Fonte.main(null);
    }//GEN-LAST:event_FonteActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        // TODO add your handling code here:
        Botões.Salvar();
    }//GEN-LAST:event_SalvarActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        // TODO add your handling code here:
        Arquivo.Abrir.main(null);
    }//GEN-LAST:event_AbrirActionPerformed

    private void displayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_displayKeyPressed

    private void displayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayKeyTyped
        // TODO add your handling code here:
                // TODO add your handling code here:
        Verificar.Linguagem();
    }//GEN-LAST:event_displayKeyTyped

    private void displayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayKeyReleased
        // TODO add your handling code here:
        Verificar.Linguagem();
             int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_EQUALS){
            Calc.Inciar();
        }
    }//GEN-LAST:event_displayKeyReleased

    private void Fonte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fonte1ActionPerformed
        // TODO add your handling code here:
        Mais.main(null);
    }//GEN-LAST:event_Fonte1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Abrir;
    private javax.swing.JButton Fonte;
    private javax.swing.JButton Fonte1;
    private javax.swing.JButton Salvar;
    public static javax.swing.JTextPane display;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
